- [what is Promise?](#what-is-promise)
- [프로미스 기본 형태](#프로미스-기본-형태)
- [프로미스의 상태](#프로미스의-상태)
- [소비자:then,catch,finally](#소비자thencatchfinally)
    - [then](#promisethen)
    - [catch](#promisecatche)
    - [finally](#finally)

<br>

# what is Promise ?
- 전통적인 비동기처리 패턴인 콜백 패턴을 보완한(콜백헬) ES6 새로운 비동기 처리 패턴

<br>

## 프로미스 기본 형태
```js
let promise = new Promise(function(resolve, reject) {
});
```
- 프로미스는 `new Promise()` 생성자 함수를 통해 인스턴스화한다
- new Promise는 executor함수를 콜백으로 받음
- executor함수는 자바스크립트 자체 제공 콜백인 resolve, reject함수를 인자로 받는다.
- executor(resolve,reject)함수는 프로미스객체 생성과 동시에 실행
// resolve 또는 reject 값을 갖는 프로미스객체가 생성됨

<br>

## 프로미스의 상태 
|상태|의미|구현|
|--|--|--|
|pending|비동기 처리가 아직 수행되지 않은 상태(executor함수가 실행되지 않은 상태)|resolve , reject 함수가 아직 호출되지 않은 상태|
|fulfilled|비동기처리가 수행된 상태(성공)|resolve함수가 호출된 상태|
|rejected|비동기 처리가 수행된 상태(실패)| reject함수가 호출된 상태|
|settled|비동기 처리가 수행된 상태(성공 또는 실패한 상태)|resolve / reject함수가 호출된 상태|

- **promise의 state와 result는 내부에 있습니다.**

>프라미스 객체의 `state`, `result 프로퍼티는` 내부 프로퍼티이므로 개발자가 직접 접근할 수 없습니다. .then/.catch/.finally 메서드를 사용시 접근 가능.


<br>

## 소비자:then,catch,finally

### promise.then()
```js
promise.then(
  function(result) { /* 결과(result)를 다룹니다 */ },
  function(error) { /* 에러(error)를 다룹니다 */ }
);
```
- then메서드는 2개의 콜백을 가질 수 있음.
- 1st CB: 이행시 실행, 2nd CB: 거부 실행   

<br>

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("완료!"), 1000);
});

// resolve 함수는 .then의 첫 번째 함수(인수)를 실행합니다.
promise.then(
  result => alert(result), // 1초 후 "완료!"를 출력
  error => alert(error) // 실행되지 않음
);
```
- 위 프로미스는 이행(resolve)되었으므로 .then메서드의 1st 콜백을 실행합니다.
- 작업이 성공적으로 처리된 경우만 다루고 싶다면 .then에 인수를 하나만 전달하면 됩니다.

<br>

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// reject 함수는 .then의 두 번째 함수를 실행합니다.
promise.then(
  result => alert(result), // 실행되지 않음
  error => alert(error) // 1초 후 "Error: 에러 발생!"을 출력
);
```
- 위 프로미스는 거부되었으므로 2nd콜백을 실행합니다.
- 일반적으로 에러처리는 `then(1stCB)(.then.then).catch(e)`로 처리합니다.

<br>

### promise.catch(e)

```js
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// .catch(f)는 promise.then(null, f)과 동일하게 작동합니다
promise.catch(alert); // 1초 뒤 "Error: 에러 발생!" 출력
```
- 프로미스 실행과정에서 발생한 에러객체를 캐치합니다.(에러처리메서드)
- 가장 마지막에 체이닝시켜도 위에서 발생한 모든 에러를 캐치

<br>

### finally
- try {...} catch {...}에 finally 절이 있는 것처럼, 프라미스에도 finally가 있습니다.
- 프라미스가 처리되면(이행이나 거부) f가 항상 실행됨.

```js
new Promise((resolve, reject) => {
  /* 시간이 걸리는 어떤 일을 수행하고, 그 후 resolve, reject를 호출함 */
})
  // 성공·실패 여부와 상관없이 프라미스가 처리되면 실행됨
  .finally(() => 로딩 인디케이터 중지)
  .then(result => result와 err 보여줌 => error 보여줌)
```
- 쓸모가 없어진 로딩 인디케이터(loading indicator)를 멈추는 경우같이, 결과가 어떻든 마무리가 필요하면 finally가 유용합니다.
- finally 핸들러엔 인수가 없습니다. 
- finally에선 프라미스가 이행되었는지, 거부되었는지 알 수 없습니다. finally에선 절차를 마무리하는 ‘보편적’ 동작을 수행하기 때문에 성공·실패 여부를 몰라도 됩니다.

<br>


```js
//[ex1 -resolve값을 넘기는 finally]

new Promise((resolve, reject) => {
  setTimeout(() => resolve("결과"), 2000)
})
  .finally(() => alert("프라미스가 준비되었습니다."))
  .then(result => alert(result)); // <-- .then에서 result를 다룰 수 있음


//[ex2 - reject된 에러를 넘기는 finally]

  new Promise((resolve, reject) => {
  throw new Error("에러 발생!");
})
  .finally(() => alert("프라미스가 준비되었습니다."))
  .catch(err => alert(err)); // <-- .catch에서 에러 객체를 다룰 수 있음
  ```
- **finally 핸들러는 자동으로 다음 핸들러에 결과와 에러를 전달합니다.**



<br>

## 출처:  
- [모던 자바스크립트 튜토리얼](https://ko.javascript.info/promise-basics#ref-393)  
- [POIEMAWEB](https://poiemaweb.com/es6-promise)
